spring.application.name=sampleproject
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/sample_project_db
spring.datasource.username=root
spring.datasource.password=2002
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# JWT Settings
jwt.secret=smartlibrarysecretkeysmartlibrarysecretkey123456
jwt.expiration=86400000

# ? Allow serving uploaded files
spring.web.resources.static-locations=classpath:/static/


# ===== Email Configuration =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tharakaisuru2000@gmail.com
spring.mail.password=bwlj fvmp svja fzsd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
